# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import kb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Никакой доп инфы нету', max_length=255, verbose_name='Имя приложения')),
                ('code', models.CharField(max_length=255, verbose_name='На латинице как во вьюхе')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Департамент, которых касается инструкция', max_length=255, verbose_name='Отдел (департамент)')),
                ('color', models.CharField(blank=True, max_length=255, verbose_name='Цвет из bootstrap')),
                ('apps', models.ManyToManyField(blank=True, help_text='Приложения с которыми работает отдел', to='kb.App', verbose_name='Приложения')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на googledocs')),
                ('file', models.FileField(blank=True, upload_to='', validators=[kb.models.validate_file_extension], verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на googledocs')),
                ('file', models.FileField(blank=True, upload_to='', validators=[kb.models.validate_file_extension], verbose_name='Файл')),
                ('departaments', models.ManyToManyField(blank=True, to='kb.Departament', verbose_name='Отделы')),
            ],
            options={
                'verbose_name': 'Пользовательская инструкция',
                'verbose_name_plural': 'Пользовательские инструкции',
            },
        ),
        migrations.CreateModel(
            name='KbUserManualName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_name', models.CharField(max_length=255)),
                ('view_path', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Название справки',
                'verbose_name_plural': 'Названия справок',
            },
        ),
        migrations.CreateModel(
            name='UserManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Копируется из kb_name', max_length=255, verbose_name='Название')),
                ('view_path', models.CharField(blank=True, max_length=255, verbose_name='view path в проекте')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('dm', models.DateTimeField(auto_now=True, verbose_name='Дата модификации')),
                ('instructions', models.ManyToManyField(related_name='usermanuals', to='kb.Instruction', verbose_name='Пользовательские инструкции')),
            ],
            options={
                'verbose_name': 'Справка',
                'verbose_name_plural': 'Справки',
            },
        ),
    ]
