# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 09:57
from __future__ import unicode_literals

from django.db import migrations


def create_apps(apps, schema_editor):
    apps_data = [
        {'name': 'ЦРМ', 'code': 'crm'},
        {'name': 'ПРОФ', 'code': 'prof'},
        {'name': 'ЛМК', 'code': 'lmk'},
        {'name': 'Аналитика', 'code': 'analytic'},
        {'name': 'Контроль качества', 'code': 'qq'},
        {'name': 'Управление', 'code': 'management'},
        {'name': 'Лаборатория', 'code': 'lab'},
        {'name': 'Предварительная запись', 'code': 'appointment'},
        {'name': 'Общее', 'code': 'mobil'},
        {'name': 'Касса', 'code': 'till'},
        {'name': 'Доставка', 'code': 'delivery'},
        {'name': 'Выезды', 'code': 'out'},
    ]
    App = apps.get_model('kb', 'App')
    for app in apps_data:
        a, created = App.objects.get_or_create(name=app['name'], code=app['code'])

def create_departaments(apps, schema_editor):
    departaments = {
        'Регистраторы': {
            'apps': ['lmk', 'prof'],
            'color': 'blue',
        },
        'Менеджеры': {
            'apps': ['crm', 'out'],
            'color': 'green'
        },
        'Проф департамент': {
            'apps': ['prof', 'crm', 'out'],
            'color': 'purple',
        },
        'Аналитики': {
            'apps': ['analytic', 'crm', 'lmk', 'prof'],
            'color': 'red'
        },
        'Контроль качества': {
            'apps': ['qq'],
            'color': 'pink'
        }
    }
    Departament = apps.get_model('kb', 'Departament')
    App = apps.get_model('kb', 'App')
    for department_name, info in departaments.items():
        apps = info.get('apps')
        color = info.get('color')
        departament, created = Departament.objects.get_or_create(name=department_name)
        app_objects = App.objects.filter(code__in=apps)
        departament.apps.set(app_objects, clear=True)
        departament.color = color
        departament.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_apps),
        migrations.RunPython(create_departaments),
    ]
